credentials:
  usernames:
    ayilmaz:
      email: afsin1977@gmail.com
      name: Afsin Yilmaz
      password: $2b$12$gOuqApdQ4.Biv41XVw2cKOcqipkE4NeTAgGp3o1XsTpMh22zXif0i
    gatehouse:
      email: warehouseoly@gmail.com
      name: Seaport Team
      password: $2b$12$JSs9ZUjKKSYXv30TMXlR/OrpWJIiEvwhGfHIQjCeuPECD6VWfYJ5S
    olysuzanodash:
      email: warehouseoly@gmail.com
      name: Awesome Guest
      password: $2b$12$817gkG6m1cNCAG4B0OuPRu1BkZbbxCTaTIyLRrY57.k0TOlpdM3j2
    warehouse:
      email: warehouseoly@gmail.com
      name: Awesome Longshore of Olympia
      password: $2b$12$yfPU0gy.MLr8Xw/biwZWTOrzdM7ww8yX.cmHufk/iM0wDpi6DNhS.
   
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - afsin1977@gmail.com
